@quanlyfilesBE_HostAddress = http://localhost:5000

### Test Database Connection
GET {{quanlyfilesBE_HostAddress}}/api/test-db
Accept: application/json

###

### Root endpoint (redirects to Swagger in Development)
GET {{quanlyfilesBE_HostAddress}}/
Accept: application/json

###
